### ISSUE TITLE
what is a blockchain board?

### ISSUE THREAD

**Issue by molleweide** [evolify/blockboard.nvim#1]
Hi there,

Can I please ask you what is a blockchain board? I don't know so much about crypto myself.

**Comment by evolify** [comment]
It used for quick view the price of some token.
![image](https://user-images.githubusercontent.com/12669069/132150336-0e5423de-ea80-4340-88db-106220e0b3db.png)

**Comment by molleweide** [comment]
Allright,

Thanks for replying!

Have a nice day :)
